name: Nekoing it

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.2.8
        with:
          api-key: ${{ secrets.NEKOWEB_API_KEY }}
          build-dir: ./
