on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # your build step here
      - name: Clean up for deploy
        run: rm -rf .git .github

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'kdaui.nekoweb.org'
          nekoweb-username: 'kdaui'
          directory: './'
